### ISSUE TITLE
Code reuse?

### ISSUE THREAD

**Issue by sdiehl** [oddvars/uplink-sdk-haskell#1]
Hi Oddvar,

Since you're linking directly against the Uplink library, you get a lot of things for free that our Java and Python SDKs have to write manually. For instance, if you import the `Account` module it has all of ToJSON / FromJSON instances already written which you can reuse for free.

Examples:

- https://github.com/adjoint-io/uplink/blob/master/src/Account.hs#L320
- https://github.com/oddvars/uplink-sdk-haskell/blob/master/src/Uplink/Client/Account.hs#L15

**Comment by oddvars** [comment]
Hi Stephen

Thanks for the input. Yes, that's the plan essentially. I started off by writing some of these by eyeballing the return from curl, but I intend to use as much from the Uplink library as I possibly can.
